name: Continuous Integration

on:
    pull_request:
        branches:
            - master
            - "releases/*"
    push:
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    test-typescript:
        name: TypeScript Tests
        runs-on: ubuntu-latest
        steps:
            - name: 💻 Checkout
              id: checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: 🔨 Setup Node.js
              id: setup-node
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
              with:
                  node-version-file: .nvmrc
                  cache: npm

            - name: 🚧 Install dependencies
              id: npm-ci
              run: npm ci

            - name: 🎨 Check format
              id: npm-format-check
              run: npm run format:check

            - name: 🔍 Lint
              id: npm-lint
              run: npm run lint

            - name: 🔄 Run tests
              id: npm-ci-test
              run: npm run ci-test

            - name: 📦 Package
              id: npm-package
              run: npm run package

    test-action:
        name: GitHub Actions Test
        runs-on: ubuntu-latest
        steps:
            - name: 💻 Checkout
              id: checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: 🔄 Test local action
              id: test-action
              uses: ./
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: master
                  seconds: 86400

            - name: 📣 Print output
              id: output
              env:
                  HAS_NEW_COMMITS: ${{ steps.test-action.outputs.has-new-commits }}
                  NEW_COMMITS_NUMBER: ${{ steps.test-action.outputs.new-commits-number }}
              run: |
                  echo "has-new-commits=$HAS_NEW_COMMITS"
                  echo "new-commits-number=$NEW_COMMITS_NUMBER"
